Update PKGBUILDs

diff --git a/git-pkgbuilds/code-git/PKGBUILD b/git-pkgbuilds/code-git/PKGBUILD
--- a/git-pkgbuilds/code-git/PKGBUILD
+++ b/git-pkgbuilds/code-git/PKGBUILD
@@ -1,135 +1,149 @@
-# Maintainer: Michael Hansen <zrax0111 gmail com>
+# Maintainer: Filipe Laíns (FFY00) <lains@archlinux.org>
+# Contributor: Michael Hansen <zrax0111 gmail com>
 # Contributor: Francisco Magalhães <franmagneto gmail com>
-# Contributor: Filipe Laíns (FFY00) <lains@archlinux.org>
 
-pkgname=code-git
-pkgdesc='The Open Source build of Visual Studio Code (vscode) editor - git latest'
+_pkgname=code
+pkgname=$_pkgname-git
+pkgdesc='The Open Source build of Visual Studio Code (vscode) editor'
+# Remember to check https://github.com/microsoft/vscode/wiki/How-to-Contribute#prerequisites for target node version
 pkgver=0
 pkgrel=1
-arch=('i686' 'x86_64' 'armv7h')
-url='https://github.com/Microsoft/vscode'
+arch=('x86_64')
+url='https://github.com/microsoft/vscode'
 license=('MIT')
-depends=('electron4' 'libsecret' 'libxkbfile' 'ripgrep')
-makedepends=('npm' 'gulp' 'python2' 'git' 'yarn' 'nodejs-lts-dubnium')
-conflicts=('visual-studio-code-git')
-provides=('visual-studio-code-git')
-
-source=("git+https://github.com/Microsoft/vscode"
-        "${pkgname}.js"
-        "${pkgname}.sh"
-        "product_json.diff"
-        "code-liveshare.diff")
+depends=('electron4' 'libsecret' 'libx11' 'libxkbfile' 'ripgrep')
+optdepends=('bash-completion: Bash completions'
+            'zsh-completions: ZSH completitons')
+makedepends=('git' 'gulp' 'npm' 'python2' 'yarn' 'nodejs-lts-dubnium')
+conflicts=('code')
+provides=('code')
+source=("$_pkgname::git+https://github.com/Microsoft/vscode"
+        'code.js'
+        'code.sh'
+        'product_json.diff'
+        'enable-proposed-apis.diff')
 sha512sums=('SKIP'
-            '889ca4d4b810b4a67319cece0e1bfeae61b33905adef64f9b27152e43e112dc53a94b1875fe0a810f0d0192dec0107aed2d01c12d6a17427db4261858f96a02a'
-            '18070c2f1af8afad4be11a1de62a2558063ee79d00097b2c8762994fa8c3e7336814c3d5387b94e54b73ccd912db4c0222c32cf5ef9f6cd73b2deb90d17c9a8c'
+            '814c9554427183cd893a33cd2cbe91f6e0ea71921ef0717c86217b1d3058d265f9ff7a9ace3e7b76f122e60b7686475cf4d999e581a1845face3033afb9f745f'
+            'dfd9ca38e6510c9ad59fb24c1141fdfeb136f457392aee79b0bc2ff378c4c54d81a06728ba3ec4039d57dfcd730c26686585de9b4032a21ee8151a4f05195c15'
             '8ec47e497287d67f37e7b669af416f43d5cdbd4574892867d7b95996ef5de53640b5bc919b06b177e1fd91cb005579d6ed0c17325117b9914ba7cf28f5f06e40'
-            '0bd10ca06dea22854e47fc45d833756ee8d7bf714c88f63feef44e0b0b5da052fba3c27d001865e3389f391cd7b888d92dc0ba44029fa5c736225da3cf2f9a46')
+            'b267dcedaf51067a782d0f14007663b706973c1538f7fb91f093475134c2145fd0ffd5ed2b47ad7f01c6167a78a4af285d2818d7850fc67a7f7a473324824664')
 
+# Even though we don't officially support other archs, let's
+# allow the user to use this PKGBUILD to compile the package
+# for his architecture
 case "$CARCH" in
-    i686)
-        _vscode_arch=ia32
-        ;;
-    x86_64)
-        _vscode_arch=x64
-        ;;
-    armv7h)
-        _vscode_arch=arm
-        ;;
-    *)
-        # Needed for mksrcinfo
-        _vscode_arch=DUMMY
-        ;;
+  i686)
+    _vscode_arch=ia32
+    ;;
+  x86_64)
+    _vscode_arch=x64
+    ;;
+  armv7h)
+    _vscode_arch=arm
+    ;;
+  *)
+    # Needed for mksrcinfo
+    _vscode_arch=DUMMY
+    ;;
 esac
 
 pkgver() {
-    cd "${srcdir}/vscode"
+    cd $_pkgname
     printf "r%s.%s" "$(git rev-list --count HEAD)" "$(git rev-parse --short HEAD)"
 }
 
 prepare() {
-    cd "${srcdir}/vscode"
+  cd $_pkgname
 
-    # This patch no longer contains proprietary modifications.
-    # See https://github.com/Microsoft/vscode/issues/31168 for details.
-    patch -p0 -i "${srcdir}/product_json.diff"
-    local _commit=$(cd "${srcdir}/vscode" && git rev-parse HEAD)
-    local _datestamp=$(date -u -Is | sed 's/\+00:00/Z/')
-    sed -e "s/@COMMIT@/${_commit}/" -e "s/@DATE@/${_datestamp}/" \
-        -i product.json
+  # This patch no longer contains proprietary modifications.
+  # See https://github.com/Microsoft/vscode/issues/31168 for details.
+  patch -p0 < ../product_json.diff
 
-    # See https://github.com/MicrosoftDocs/live-share/issues/262 for details
-    patch -p1 -i "${srcdir}/code-liveshare.diff"
+  # Set the commit and build date
+  local _commit=$(git rev-parse HEAD)
+  local _datestamp=$(date -u -Is | sed 's/\+00:00/Z/')
+  sed -e "s/@COMMIT@/$_commit/" -e "s/@DATE@/$_datestamp/" -i product.json
 
-    # Build native modules for system electron
-    local _target=$(</usr/lib/electron4/version)
-    sed -i "s/^target .*/target \"${_target//v/}\"/" .yarnrc
+  # See https://github.com/MicrosoftDocs/live-share/issues/262 for details
+  # Also, https://github.com/microsoft/vscode/issues/48946
+  patch -p1 < ../enable-proposed-apis.diff
 
-    # Patch appdata and desktop file
-    sed -i 's|/usr/share/@@NAME@@/@@NAME@@|@@NAME@@|g
-            s|@@NAME_SHORT@@|Code - Git|g
-            s|@@NAME_LONG@@|Code - Git|g
-            s|@@NAME@@|code-git|g
-            s|@@ICON@@|code-git|g
-            s|@@LICENSE@@|MIT|g
-            s|inode/directory;||' resources/linux/code.{appdata.xml,desktop}
+  # Build native modules for system electron
+  local _target=$(</usr/lib/electron4/version)
+  sed -i "s/^target .*/target \"${_target//v/}\"/" .yarnrc
 
-    # Fix bin path
-    sed -i "s|return path.join(path.dirname(execPath), 'bin', \`\${product.applicationName}\`);|return '/usr/bin/${pkgname}';|g
-            s|return path.join(appRoot, 'scripts', 'code-cli.sh');|return '/usr/bin/${pkgname}';|g" \
-        src/vs/platform/environment/node/environmentService.ts
+  # Patch appdata and desktop file
+  sed -i 's|/usr/share/@@NAME@@/@@NAME@@|@@NAME@@|g
+          s|@@NAME_SHORT@@|Code|g
+          s|@@NAME_LONG@@|Code - OSS|g
+          s|@@NAME@@|code-oss|g
+          s|@@ICON@@|code-oss|g
+          s|@@LICENSE@@|MIT|g
+          s|inode/directory;||' resources/linux/code{.appdata.xml,.desktop,-url-handler.desktop}
+
+  # Add missing exectable name to bash completion
+  sed -i 's|complete -F _code code|complete -F _code code code-oss|' resources/completions/bash/code
+  # Create new zsh completion file for our binary
+  cp resources/completions/zsh/_code resources/completions/zsh/_code-oss
+  sed -i 's|#compdef code|#compdef code code-oss|' resources/completions/zsh/_code-oss
+
+  # Fix bin path
+  sed -i "s|return path.join(path.dirname(execPath), 'bin', \`\${product.applicationName}\`);|return '/usr/bin/code';|g
+          s|return path.join(appRoot, 'scripts', 'code-cli.sh');|return '/usr/bin/code';|g" \
+          src/vs/platform/environment/node/environmentService.ts
 }
 
 build() {
-    # https://github.com/mapbox/node-sqlite3/issues/1044
-    mkdir -p path
-    ln -sf /usr/bin/python2 path/python
-    export PATH="$PWD/path:$PATH"
+  # https://github.com/mapbox/node-sqlite3/issues/1044
+  mkdir -p path
+  ln -sf /usr/bin/python2 path/python
+  export PATH="$PWD/path:$PATH"
 
-    cd "${srcdir}/vscode"
+  cd $_pkgname
 
-    yarn install --arch=${_vscode_arch}
+  yarn install --arch=$_vscode_arch
 
-    # The default memory limit may be too low for current versions of node
-    # to successfully build vscode.  Uncomment this to set it to 2GB, or
-    # change it if this number still doesn't work for your system.
-    mem_limit="--max_old_space_size=8096"
+  # The default memory limit may be too low for current versions of node
+  # to successfully build vscode. Change it if this number still doesn't
+  # work for your system.
+  mem_limit="--max_old_space_size=9000"
 
-    if ! /usr/bin/node $mem_limit /usr/bin/gulp vscode-linux-${_vscode_arch}-min
-    then
-        echo
-        echo "*** NOTE: If the build failed due to running out of file handles (EMFILE),"
-        echo "*** you will need to raise your max open file limit."
-        echo "*** You can check this for more information on how to increase this limit:"
-        echo "***    https://ro-che.info/articles/2017-03-26-increase-open-files-limit"
-        exit 1
-    fi
+  if ! /usr/bin/node $mem_limit /usr/bin/gulp vscode-linux-$_vscode_arch-min
+  then
+      echo
+      echo "*** NOTE: If the build failed due to running out of file handles (EMFILE),"
+      echo "*** you will need to raise your max open file limit."
+      echo "*** You can check this for more information on how to increase this limit:"
+      echo "***    https://ro-che.info/articles/2017-03-26-increase-open-files-limit"
+      exit 1
+  fi
 }
 
 package() {
-    install -dm 755 "${pkgdir}/usr/lib/${pkgname}"
-    cp -r --no-preserve=ownership --preserve=mode \
-        VSCode-linux-${_vscode_arch}/resources/app/* \
-        "${pkgdir}/usr/lib/${pkgname}"
+  # Install resource files
+  install -dm 755 "$pkgdir"/usr/lib/$_pkgname
+  cp -r --no-preserve=ownership --preserve=mode VSCode-linux-$_vscode_arch/resources/app/* "$pkgdir"/usr/lib/$_pkgname/
 
-    # Replace statically included binary with system version
-    ln -sf /usr/bin/rg \
-            "${pkgdir}/usr/lib/${pkgname}/node_modules.asar.unpacked/vscode-ripgrep/bin/rg"
+  # replace statically included binary with system copy
+  ln -sf /usr/bin/rg "$pkgdir"/usr/lib/code/node_modules.asar.unpacked/vscode-ripgrep/bin/rg
 
-    # Put the startup script in /usr/bin
-    install -Dm 755 ${pkgname}.sh "${pkgdir}/usr/bin/${pkgname}"
-    install -Dm 755 ${pkgname}.js "${pkgdir}/usr/lib/${pkgname}/${pkgname}.js"
+  # Install binary
+  install -Dm 755 code.sh "$pkgdir"/usr/bin/code-oss
+  install -Dm 755 code.js "$pkgdir"/usr/lib/$_pkgname/code.js
+  ln -sf /usr/bin/code-oss "$pkgdir"/usr/bin/code
 
-    # Install appdata and desktop file
-    install -Dm 644 vscode/resources/linux/code.appdata.xml \
-            "${pkgdir}/usr/share/metainfo/${pkgname}.appdata.xml"
-    install -Dm 644 vscode/resources/linux/code.desktop \
-            "${pkgdir}/usr/share/applications/${pkgname}.desktop"
-    install -Dm 644 VSCode-linux-${_vscode_arch}/resources/app/resources/linux/code.png \
-            "${pkgdir}/usr/share/pixmaps/${pkgname}.png"
+  # Install appdata and desktop file
+  install -Dm 644 $_pkgname/resources/linux/code.appdata.xml "$pkgdir"/usr/share/metainfo/code-oss.appdata.xml
+  install -Dm 644 $_pkgname/resources/linux/code.desktop "$pkgdir"/usr/share/applications/code-oss.desktop
+  install -Dm 644 $_pkgname/resources/linux/code-url-handler.desktop "$pkgdir"/usr/share/applications/code-oss-url-handler.desktop
+  install -Dm 644 VSCode-linux-$_vscode_arch/resources/app/resources/linux/code.png "$pkgdir"/usr/share/pixmaps/code-oss.png
 
-    # Install license files
-    install -Dm 644 "${srcdir}/VSCode-linux-${_vscode_arch}/resources/app/LICENSE.txt" \
-            "${pkgdir}/usr/share/licenses/${pkgname}/LICENSE"
-    install -Dm 644 "${srcdir}/VSCode-linux-${_vscode_arch}/resources/app/ThirdPartyNotices.txt" \
-            "${pkgdir}/usr/share/licenses/${pkgname}/ThirdPartyNotices.txt"
+  # Install bash and zsh completions
+  install -Dm 644 $_pkgname/resources/completions/bash/code "$pkgdir"/usr/share/bash-completion/completions/code-oss
+  ln -s code-oss "$pkgdir"/usr/share/bash-completion/completions/code
+  install -Dm 644 $_pkgname/resources/completions/zsh/_code-oss "$pkgdir"/usr/share/zsh/site-functions/_code-oss
+
+  # Install license files
+  install -Dm 644 VSCode-linux-$_vscode_arch/resources/app/LICENSE.txt "$pkgdir"/usr/share/licenses/$_pkgname/LICENSE
+  install -Dm 644 VSCode-linux-$_vscode_arch/resources/app/ThirdPartyNotices.txt "$pkgdir"/usr/share/licenses/$_pkgname/ThirdPartyNotices.txt
 }
